AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for sd-webui EC2 instance'

Resources:

  WebUIEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: g4dn.xlarge
      ImageId: ami-0750979b79a8dd679 #Change this to ami in your reagion with pytorch installed
      KeyName: webui
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp3
            VolumeSize: 100 #change this to your preferences
      AvailabilityZone: eu-central-1a #change this to your region where you have access to xlarge G Instance
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            apt-get update
            apt-get install -y wget unzip
            cd /home/ubuntu
            wget https://github.com/cmdr2/stable-diffusion-ui/releases/download/v2.5.24/Easy-Diffusion-Linux.zip
            unzip Easy-Diffusion-Linux.zip
            chown -R ubuntu:ubuntu easy-diffusion  # Set ownership to ubuntu user
            chmod -R +x easy-diffusion  # Set executable permissions recursively
            cd easy-diffusion
            chmod +x start.sh
            ./start.sh & # Running in the background
            while ! nc -z localhost 9000; do   
            sleep 1
            done      
            sleep 30
            cd models/stable-diffusion
            sudo wget https://civitai.com/api/download/models/176040 --content-disposition  # Am I real
            sudo wget https://civitai.com/api/download/models/181248 --content-disposition  # Virile-reality
            sudo wget https://civitai.com/api/download/models/172160 --content-disposition  # Copax TimeLessXL
            cd ../lora
            sudo wget https://civitai.com/api/download/models/152309 --content-disposition  # Lora
      SecurityGroupIds:
        - !Ref WebUISecurityGroup
      Tags:
        - Key: Name
          Value: sd-webui

  WebUISecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow all traffic
      SecurityGroupIngress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: sd-webui-sg

Outputs:
  WebUIInstancePublicIP:
    Description: 'Public IP of the EC2 instance'
    Value: !GetAtt WebUIEC2Instance.PublicIp
